# controller_manager:
#   ros_parameters:
#     update_rate: 30
#     use_sim_time: true

#     diff_cont:
#       type: diff_drive_controller/DiffDriveController
    
#     joint_broad:
#       type: joint_state_broadcaster/JointStateBroadcaster

# diff_cont:
#   ros_parameters:

#     publish_rate: 50.0

#     base_frame_id: base_link
    
#     left_wheel_names: ['left_wheel_joint']
#     right_wheel_names: ['right_wheel_joint']

#     wheel_separation: 0.32
#     wheel_radius: 0.033

#     use_stamped_vel: false

# Publish all joint states -----------------------------------
joint_states_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  #50


motor_velocity_controller_1:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

motor_velocity_controller_2:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}